[package]
name = "pyro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyro-core]
path = "../pyro-core"

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies]
eyre = "0.6"
