[package]
name = "pyro-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyro-core]
path = "../pyro-core"

[dependencies.tokio]
version = "1"
features = ["sync"]

[dependencies]
eyre = "0.6"